version: '2'
services:
  php:
    restart: always
    image: ccr.ccs.tencentyun.com/qyy-base/qyy-php:2.0.0
    container_name: php
    volumes:
    - /c/Users/cc:/home/worker/data/www/ibos-qyy-group/ibosapi
    - ./php/php-fpm.ini:/home/worker/php/etc/php-fpm.ini
    - ./php/php-fpm.conf:/home/worker/php/etc/php-fpm.conf
    - ./php/php.d/xdebug.ini:/home/worker/php/etc/php.d/xdebug.ini
    - ./nginx/nginx.conf:/home/worker/nginx/conf/nginx.conf
    - ./nginx/conf.d:/home/worker/nginx/conf.d
    - ./init.sh:/etc/my_init.d/init.sh
    ports:
      - "80:80"
    networks:
      - dev
    depends_on:
      - redis
      - mysql
    extra_hosts:
      - "wqdapi.cc:192.168.99.100"
      - "ld.cc:192.168.99.100"
      - "ibosapi.cc:192.168.99.100"
      - "open.qunyingyong.net:192.168.99.100"
      - "wp.cc:192.168.99.100"
      - "qyyadmin.cc:192.168.99.100"
  redis:
    restart: always
    image:  registry.cn-hangzhou.aliyuncs.com/qyyteam/redis:1.0.0
    ports:
      - "6379:6379"
    volumes:
      - /c/Users/redis:/data
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    networks:
      - dev 
    container_name: redis
  mysql:
    image: registry.cn-hangzhou.aliyuncs.com/qyyteam/mysql:5.6
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/my.cnf:/etc/mysql/my.cnf
      - ./mysql/conf.d:/etc/mysql/conf.d
      - /mnt/sda1/mysql/data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
    networks:
      - dev 
    container_name: mysql
networks:
    dev: